# Generated by Django 2.0.4 on 2018-10-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20181013_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_list',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='food_list',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='food_list',
            name='type',
            field=models.CharField(choices=[('chinese', 'Chinese'), ('indian', 'Indian'), ('mexican', 'Mexican'), ('italian', 'Italian'), ('others', 'Others')], default='other', max_length=20),
        ),
    ]
