# Generated by Django 2.0.4 on 2018-10-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20181015_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_list',
            name='type',
            field=models.CharField(choices=[('chinese', 'Chinese'), ('indian', 'Indian'), ('mexican', 'Mexican'), ('italian', 'Italian'), ('thai', 'Thai'), ('french', 'French'), ('greek', 'Greek'), ('others', 'Others')], default='other', max_length=20),
        ),
    ]
